### ISSUE TITLE
path error

### ISSUE THREAD

**Issue by robjhyndman** [ketan/BeautifyLatex#2]
I've installed in Sublimetext 3 Build 3083 on Ubuntu 15.04. When I run it, I get the following error:

```
Error: can't specify None for path argument
```

**Comment by ketan** [comment]
Do you have `latexindent.pl` or `latexindent.exe` on your path? You can get it from here - https://github.com/cmhughes/latexindent.pl

**Comment by robjhyndman** [comment]
Got it. I had assumed that was downloaded when the plug in was installed.
