### ISSUE TITLE
Possibly need update due to update of latexindent.pl

### ISSUE THREAD

**Issue by jasjuang** [ketan/BeautifyLatex#6]
Suppose I create a random .tex file and name it test.tex.

If I am at a terminal and type latexindent.pl test.tex it works so the path should be set properly, but if I open Sublime and set run_on_save as true and then save the below error pops up

The file /tmp/tmpvqemhw exists , but the extension does not correspond to any given in fileExtensionPreference;
consinder updating fileExtensionPreference.

Exiting, no indentation done.

I am on Ubuntu 14.04, beautify latex used to work, but after I pulled the newest latexindent.pl it stops working. Would appreciate if you can fix it!

**Comment by jdumas** [comment]
This can be fixed easily by creating a named temporary file with the correct extension. Apply the following patch to `beautify_latex.py`:

```
36,37c36,38
<     with tempfile.NamedTemporaryFile(delete=False) as temp:
<       try: 
---
>     ext = os.path.splitext(self.view.file_name())[1]
>     with tempfile.NamedTemporaryFile(delete=False,suffix=ext) as temp:
>       try:
```

**Comment by jasjuang** [comment]
thanks @jdumas your fix works for me, I will submit a PR

**Comment by flipphillips** [comment]
FWIW, I was having additional trouble w/ `latexindent` with respect to the Perl distribution in macOS Sierra, which I fixed (doesn't involve this bug, but is a breadcrumb for folks who stumble here like me) by installing them manually. The problem that @jasjuang had also appears in macOS (only the temp files look like the wonderfully chaotic `/var/folders/rn/0n7d7l7d3tz9g5hp4p2lbgvm0000gn/T/tmp_utte4`
). Patching as noted above fixes that problem on macOS sierra.
