### ISSUE TITLE
Problem due to `latexindent` vs `latexindent.pl`

### ISSUE THREAD

**Issue by chengchou** [ketan/BeautifyLatex#8]
This issue is based on my [question](http://tex.stackexchange.com/questions/326600/use-latexindent-pl-with-beautifylatex-in-sublime-text/326619?noredirect=1#comment799934_326619) on tex.stackexchange.com. 

**Problem**: I installed `BeautifyLatex` in SublimeText 3 on OS X El Capitan . When I tried to save tex file, there was an error:

```
Error: can't specify None for path argument
```

I can see that my `latexindent` was installed by typing `which latexindent` in the terminal.

```
$ which latexindent
/Library/TeX/texbin/latexindent
```

After installing [`Fix Mac Path`](https://packagecontrol.io/packages/Fix%20Mac%20Path) and  adding `"additional_path_items": ["/Library/TeX/texbin"]` in the user settings of `BeautifyLatex` (kindly suggested by the user **r-stein** in [tex.stackexchange](http://tex.stackexchange.com/questions/326600/use-latexindent-pl-with-beautifylatex-in-sublime-text/326619?noredirect=1#comment799934_326619). _The error still exists._

**Solution**: One user (**ig0774**) in [tex.stackexchange.com](http://tex.stackexchange.com/questions/326600/use-latexindent-pl-with-beautifylatex-in-sublime-text/326619?noredirect=1#comment799934_326619)  suggested to link `latexindent.pl` to `latexindent` in the terminal.

```
$ sudo ln -s /Library/TeX/texbin/latexindent /Library/TeX/texbin/latexindent.pl
```

After that, `BeautifyLatex` is up and running. (You need to install `Fix Mac Path` and add the path first.)

**Comments that could be helpful to others:** At first, my `latexindent` does not work at all even in the terminal environment. After `cd` to the directory `/Library/TeX/texbin/` that contains `latexindent`, I typed `perl latexindent` and received some error message telling me that `YAML::Tiny` was missing. After typing the following in the terminal, I managed to make `latexindent` start working in terminal, but not in the sublime text.

```
$ sudo cpan App::cpanminus
$ sudo cpanm YAML::Tiny
$ sudo perl -MCPAN -e 'install "File::HomeDir"'
```

**Comment by ketan** [comment]
This is very useful information. Do you think you could add something to the readme with a link to this issue?

**Comment by chengchou** [comment]
Done. I added a section for installing beautifylatex on mac in the readme file.

**Comment by ketan** [comment]
Do you mind submitting a pull request, so that other users who come here might find it?

**Comment by chengchou** [comment]
Of course, I submitted a pull request. Did I do it correctly? I am new to github.

**Comment by ketan** [comment]
> Of course, I submitted a pull request. Did I do it correctly? I am new to github.

Yes, you did it just fine. I can see this section in the readme — https://github.com/ketan/BeautifyLatex#note-for-mac-users.

Thank you very much.
